server:
  mode: debug
  port: :8081
  sessionname: firesession
  sessionkey: 5b25e00c5f15030007661881
db:
  dialect: mysql
  url: root:zxcvbnm123@tcp(127.0.0.1:3306)/test?charset=utf8&parseTime=true&loc=Local
  maxopen: 100
  maxlife: 120
  maxidle: 10
  logenable: true
