server:
  mode: release
  port: :8081
  sessionname: firesession
  sessionkey: 5b25e00c5f15030007661881
db:
  dialect: mysql
  user: root
  password: 9o0p-[=]
  database: tel_site
  host: 192.168.50.16:3307
  maxopen: 100
  maxlife: 120
  maxidle: 10
  logenable: true
